# Don't change this! Version used to track needed updates.
version = 0
axeStripParticles = true
axeScrapeParticlesDisplayType = "DEFAULT"
axeWaxOffParticlesDisplayType = "DEFAULT"
boneMealUsingParticles = true
flintAndSteelParticles = true
increasedItemBreakParticles = true
waterEvaporateFromBucketSteam = true
waterBucketUseParticles = true
lavaBucketUseParticles = true
powderSnowBucketUseParticles = true
lingeringPotionClouds = true
splashPotionClouds = true
structureVoidItemMarker = true

[itemRarity]
particlesDisplayType = "ON"
particleColorType = "NAME_COLOR"
mixedColorName = true
useItemBorder = true
colorOverrides = [  ]
particleMaxHeight = 1.0
particleMaxSpeed = 1.0
particleDensity = 0.25

[projectiles]
enderPearlTrailDensity = 0.5
xpBottleParticlesDisplayType = "DEFAULT"
xpBottleParticlesDensity = 15
eggSmashSoundVolume = 0.5
eggSplatParticles = true
snowballTrailDensity = 0.5
snowballPoofsHaveSnowflakes = true
snowballPoofSoundVolume = 0.3