#Client configs
#Enable number shortening. E.g. 1000000 becomes 1M.
"Enable number shortening" = true
#The colour of the exact count tooltip shown on items.
#Available colours (case insensitive):
#apollyon,
#aqua,
#black,
#blue,
#dark_aqua,
#dark_blue,
#dark_gray,
#dark_green,
#dark_purple,
#dark_red,
#gold,
#gr_eden,
#gr_frost,
#gr_spider,
#gray,
#green,
#light_purple,
#middle,
#red,
#white,
#yellow
"Exact count number colour" = "dark_aqua"

