
[covenant_of_the_seven_curses]
	#Maximum ceiling for the exponential growth multiplier when using LP to cast spells
	#Default: 30
	#Range: 1 ~ 100
	levelScale = 30
	#Fixed multiplier for COMMON spells when using LP to cast spells
	#Default: 2
	#Range: 1 ~ 100
	commonMultiplier = 2
	#Fixed multiplier for UNCOMMON spells when using LP to cast spells
	#Default: 3
	#Range: 1 ~ 100
	uncommonMultiplier = 3
	#Fixed multiplier for RARE spells when using LP to cast spells
	#Default: 7
	#Range: 1 ~ 100
	rareMultiplier = 7
	#Fixed multiplier for EPIC spells when using LP to cast spells
	#Default: 12
	#Range: 1 ~ 100
	epicMultiplier = 12
	#Fixed multiplier for LEGENDARY spells when using LP to cast spells
	#Default: 25
	#Range: 1 ~ 100
	legendaryMultiplier = 25
	#Disables Iron's Spells 'n Spellbooks' Mana Bar from rendering. Band-aid fix for mana unification mods that mess with it.
	#Default: false
	disableManaBar = true

