onCull = false
MaxEntityEntities = 1024
qualityModes = "ULTRA"
RenderWeather = "NORMAL"
FastItemRender = false
RenderDisplayItem = false
blackListedEntities = []
whiteListedEntities = ["minecraft:player"]
BlackTagListEntity = []
WhiteTagListEntity = []
isAlwaysShowItemCount = true
startTime = 72.922
onGui = false
GuiRXTX = false
GuiFPS = false
GuiCPU = false
GuiGPU = false
GuiRAM = false
GuiEntityCount = false
GuiPlayerPos = false
GuiServer = false
GuiCameraTarget = false
Mood = false
MaxParticleDistance = 512
WhiteListedParticle = []
BlackListedParticle = []
GuiEasyRamMode = true
GuiDisplayRamUsage = false
GuiX = 0
GuiY = 0
UseAui = false
DeBug = false
TextBackground = false
TextureAnimatedSprites = true
SoundDevicesMonitor = false
SetParticleMaxAge = false
ParticleMaxAge = 1
GuiViewMode = "EMPTY"
MinDistance = 16
EntityDistance = 512
TickPerformance = true
ParticlePerformance = false
EntityPerformance = false
EntityViewDebug = false
ParticleCountLimit = 16384
BlockBreakParticle = true
AsyncCompute = true
