
["Boss Health"]
	#Health for specified mob.
	"Gob, King of Gnomes Health" = 3000.0
	#Health for specified mob.
	"Super Sniffer Health" = 4000.0
	#Health for specified mob.
	"Ultra Sniffer Health" = 545000.0
	#Health for specified mob.
	"Trial Guardian Health" = 11000.0
	#Health for specified mob.
	"Virtue Health" = 15000.0
	#Health for specified mob.
	"Enchanter Merlin Health" = 15001.0
	#Health for specified mob.
	"Sorceress Circe Health" = 12501.0
	#Health for specified mob.
	"Archmage Gundalf Health" = 35000.0
	#Health for specified mob.
	"Multiplayer Boss Health Scaling" = true

["Mob Health"]
	#Health for specified mob.
	"Duskrok Health" = 150.0
	#Health for specified mob.
	"Hellrok Health" = 250.0

[Bosses]
	#If true, Terramity bosses will despawn after you die.
	"Can Bosses Despawn" = true

["Mob Griefing"]
	#If false, Terramity mobs will (mostly) not damage terrain.
	MobGriefing = false

